---
title: 'Allen: covariates and batch effects'
author: "Davide Risso"
date: "2/10/2016"
output: 
  html_document: 
    fig_height: 7
    fig_width: 7
    toc: yes
    code_folding: hide
    toc_float: yes
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=TRUE)
library(SummarizedExperiment)
library(scRNAseq)
library(zinb)
library(ggplot2)
library(magrittr)
library(matrixStats)
library(Rtsne)
library(scone)
library(RColorBrewer)
library(cluster)
library(parallel)
library(EDASeq)
library(digest)
library(edgeR)
library(DESeq2)

set.seed(8283)
options(getClass.msg=FALSE) #get rid of annoying messages about cache until fixed internally in R

ncores <- 11
```

Here, I will explore the relation between the expression values and some covariates provided with the data.

```{r datain}
data("allen")
allen_core <- allen[grep("^ERCC-", rownames(allen), invert = TRUE),
                    which(colData(allen)$Core.Type=="Core")]

filter <- rowSums(assay(allen_core)>10)>=10
```

# Comparison of methods

```{r normalization}
raw <- assay(allen_core)[filter,]

totalcount = function (ei)
{
  sums = colSums(ei)
  eo = t(t(ei)*mean(sums)/sums)
  return(eo)
}

tc <- totalcount(raw)
fq <- FQT_FN(raw)
tmm <- TMM_FN(raw)
deseq <- DESEQ_FN(raw)
```

## PCA

```{r pca}
library(rARPACK)
fastpca <- function(expr, scale=FALSE) {
  svd_raw <- svds(scale(t(expr), center=TRUE, scale=scale), k=3, nu=3, nv=0)
  pc_raw <- svd_raw$u %*% diag(svd_raw$d[1:3])
  return(pc_raw)
}

pc_raw <- fastpca(log1p(raw))
pc_tc <- fastpca(log1p(tc))
pc_fq <- fastpca(log1p(fq))
pc_tmm <- fastpca(log1p(tmm))
pc_deseq <- fastpca(log1p(deseq))

col1 <- brewer.pal(9, "Set1")
col2 <- brewer.pal(8, "Set2")

level1 <- as.factor(colData(allen_core)$driver_1_s)
colMerged <- col1[level1]
plot(pc_raw, col=colMerged, pch=20, main="PCA RAW")
legend("bottomright", levels(level1), fill=col1)

plot(pc_tc, col=colMerged, pch=20, main="PCA TC")
plot(pc_tmm, col=colMerged, pch=20, main="PCA TMM")
plot(pc_fq, col=colMerged, pch=20, main="PCA FQ")
```

## ZIFA

```{r zifa}
wrapRzifa <- function(Y, block = T){
  # wrapper R function for ZIFA.
  # md5 hashing and temporary files are used not to re-run zifa 
  # if it has already be run on this computer.
  d = digest(Y, "md5")
  tmp = paste0(tempdir(), '/', d)
  write.csv(Y, paste0(tmp, '.csv'))
  
  if (!file.exists(paste0(tmp, '_zifa.csv'))){
    print('run ZIFA')
    bb = ifelse(block, '-b ', '')
    cmd = sprintf('python run_zifa.py %s%s.csv %s_zifa.csv', bb, tmp, tmp)
    system(cmd)
  }
  read.csv(sprintf("%s_zifa.csv", tmp), header=FALSE)
}

zifa_raw <- wrapRzifa(log1p(raw))
plot(zifa_raw, pch=19, col=colMerged, main="ZIFA Raw")

zifa_tc <- wrapRzifa(log1p(tc))
plot(zifa_tc, pch=19, col=colMerged, main="ZIFA TC")

zifa_tmm <- wrapRzifa(log1p(tmm))
plot(zifa_tmm, pch=19, col=colMerged, main="ZIFA TMM")

zifa_fq <- wrapRzifa(log1p(fq))
plot(zifa_fq, pch=19, col=colMerged, main="ZIFA FQ")
```

## ZINB

```{r zinb}
zinb <- zinbFit(raw, ncores = ncores, K = 2)
plot(zinb@W, pch=19, col=colMerged, main="ZINB")
```

# Sample-level covariates

## PCA

Here, we look at PCA (using TC normalization) to see which covariates influence the data.

```{r pca_cov}
detection_rate <- colSums(raw>0)
coverage <- colSums(raw)

df <- cbind(data.frame(PC1=pc_tc[,1], PC2=pc_tc[,2], coverage=coverage, detection_rate=detection_rate), as.data.frame(colData(allen_core)[,1:15]))

df %>% ggplot(aes(PC1, PC2)) + geom_point(aes(color=coverage)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

df %>% ggplot(aes(PC1, PC2)) + geom_point(aes(color=detection_rate)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

pairs(df[,1:4], col=colMerged, pch=19)

cors <- sapply(1:3, function(i) cor(pc_tc[,i], df[,3:19]))
colnames(cors) <- paste("PC", 1:NCOL(cors), sep="")
rownames(cors) <- paste("QC", 1:NROW(cors), sep="")
barplot(abs(cors), beside = TRUE, col=rainbow(17), border=rainbow(17), ylim=c(0, 1), space=c(0, 2), main="Absolute correlation with QC features")
legend("topright", colnames(df)[3:19], fill=rainbow(17), border=rainbow(17), cex=.5)
```

## ZIFA

```{r zifa_cov}
df <- cbind(data.frame(Z1=zifa_tc[,1], Z2=zifa_tc[,2], coverage=coverage, detection_rate=detection_rate), as.data.frame(colData(allen_core)[,1:15]))

df %>% ggplot(aes(Z1, Z2)) + geom_point(aes(color=coverage)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

df %>% ggplot(aes(Z1, Z2)) + geom_point(aes(color=detection_rate)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

pairs(df, col=colMerged, pch=19)

cors <- sapply(1:2, function(i) cor(zifa_tc[,i], df[,3:19]))
colnames(cors) <- paste("PC", 1:NCOL(cors), sep="")
rownames(cors) <- paste("QC", 1:NROW(cors), sep="")
barplot(abs(cors), beside = TRUE, col=rainbow(17), border=rainbow(17), ylim=c(0, 1), space=c(0, 2), main="Absolute correlation with QC features")
legend("topright", colnames(df)[3:19], fill=rainbow(17), border=rainbow(17), cex=1)
```

## ZINB

```{r zinb_cov}
df <- cbind(data.frame(W1=zinb@W[,1], W2=zinb@W[,2], coverage=coverage, detection_rate=detection_rate), as.data.frame(colData(allen_core)[,1:15]))

df %>% ggplot(aes(W1, W2)) + geom_point(aes(color=coverage)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

df %>% ggplot(aes(W1, W2)) + geom_point(aes(color=detection_rate)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

pairs(df, col=colMerged, pch=19)

cors <- sapply(1:2, function(i) cor(zinb@W[,i], df[,3:19]))
colnames(cors) <- paste("PC", 1:NCOL(cors), sep="")
rownames(cors) <- paste("QC", 1:NROW(cors), sep="")
barplot(abs(cors), beside = TRUE, col=rainbow(17), border=rainbow(17), ylim=c(0, 1), space=c(0, 2), main="Absolute correlation with QC features")
legend("topright", colnames(df)[3:19], fill=rainbow(17), border=rainbow(17), cex=1)
```

## Add QC features in ZINB model

```{r zinb_batch, eval=FALSE}
qcpca <- prcomp(as.matrix(colData(allen_core)[,1:15]), center=TRUE, scale=TRUE)
zinb_batch <- zinbFit(raw, ncores = ncores, K = 2, X=qcpca$x[,1:2])
plot(zinb_batch@W, pch=19, col=colMerged, main="ZINB")
```

```{r zinb_batch_cov, eval=FALSE}
plot(zinb_batch@W, col=colBatch, pch=20, main="Colored by batch")

plot(zinb_batch@W, col=colPos, pch=20, main="Colored by position")

df <- data.frame(W1=zinb_batch@W[,1], W2=zinb_batch@W[,2], nmolecule=nmolecule, diameter=diameter, coverage=coverage, detection_rate=detection_rate) 

df %>% ggplot(aes(W1, W2)) + geom_point(aes(color=nmolecule)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

df %>% ggplot(aes(W1, W2)) + geom_point(aes(color=diameter)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

df %>% ggplot(aes(W1, W2)) + geom_point(aes(color=coverage)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

df %>% ggplot(aes(W1, W2)) + geom_point(aes(color=detection_rate)) + scale_colour_gradient(low="blue", high="yellow") + theme_classic()

pairs(df, col=colMerged, pch=19)

cors <- sapply(1:2, function(i) cor(zinb_batch@W[,i], df[,3:19]))
colnames(cors) <- paste("PC", 1:NCOL(cors), sep="")
rownames(cors) <- paste("QC", 1:NROW(cors), sep="")
barplot(abs(cors), beside = TRUE, col=rainbow(17), border=rainbow(17), ylim=c(0, 1), space=c(0, 2), main="Absolute correlation with QC features")
legend("topright", colnames(df)[3:19], fill=rainbow(17), border=rainbow(17), cex=1)
```


# Gene-level covariates

```{r gc_content, eval=FALSE}
counts <- counts[bm[,1],]
gene_info = getGeneLengthAndGCContent(as.character(bm[,2]), "mm10", mode="org.db")
rownames(gene_info) = bm[,1]
gene_info = na.omit(gene_info)
```
