---
title: "ComBat on expresso"
author: "Fanny Perraudeau"
date: "07/31/2017"
output: 
  html_document: 
  fig_height: 10
fig_width: 10
toc: yes
code_folding: hide
toc_float: yes
---
```{r options, echo=FALSE, results="hide",message=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=TRUE, fig.width=6, fig.height=6)
library(sva) #for ComBat
library(doParallel)
library(BiocParallel)
library(scRNAseq)
library(RColorBrewer)
library(rARPACK)
```

```{r par}
NCORES = 2
registerDoParallel(NCORES)
register(DoparParam())
```

# Data

```{r datain}
all.counts <- read.table("ESpresso/counttable_es.csv", header=TRUE, row.names=1, colClasses=c("character", rep("integer", 704)))
serum <- sub("ola_mES_([^_]+)_.*", "\\1", colnames(all.counts))
batch <- sub("ola_mES_[^_]+_([^_]+)_.*", "\\1", colnames(all.counts))
targets <- data.frame(Serum=serum, Batch=batch)

# Only using data from two batches.
keep <- targets$Batch %in% c("2", "3")
all.counts <- all.counts[,keep]
targets <- targets[keep,]
targets$Plate <- as.integer(factor(paste0(targets$Serum, targets$Batch)))
targets[] <- lapply(targets, factor)
targets$Serum <- factor(targets$Serum, c("lif", "2i", "a2i"))

# Removing spike-ins.
is.mouse <- grepl("^ENSMUSG", rownames(all.counts))
all.counts <- all.counts[is.mouse,]

col1 <- brewer.pal(9, "Set1")
col2 <- c(brewer.pal(8, "Set2"), brewer.pal(8, "Set3"), brewer.pal(8, "Set1"))

detection_rate <- colSums(all.counts>0)
coverage <- colSums(all.counts)
```

```{r normalization}
filter <- rowSums(all.counts>10)>=10
raw <- all.counts[filter,]
fq <- FQT_FN(raw)

vars <- rowVars(log1p(fq))
names(vars) <- rownames(fq)
vars <- sort(vars, decreasing = TRUE)
vargenes <- names(vars)[1:1000]

core = log1p(fq[vargenes, ])
```

# ComBat

```{r}
combat <- ComBat(dat=core, batch=batch, par.prior=TRUE, prior.plots=TRUE)
```

# Dim. Red.

## PCA

```{r}
fastpca <- function(expr, scale=FALSE) {
  svd_raw <- svds(scale(t(expr), center=TRUE, scale=scale), k=3, nu=3, nv=0)
  pc_raw <- svd_raw$u %*% diag(svd_raw$d[1:3])
  return(pc_raw)
}

pc_combat <- fastpca(combat)
```

```{r}
colMerged <- col1[targets$Serum]
plot(pc_combat, col=colMerged, pch=20, main="PCA after Combat")
legend("topleft", levels(targets$Serum), fill=col1)
```

## ZIFA

```{r zifa}
wrapRzifa <- function(Y, block = TRUE, k=2){
  # wrapper R function for ZIFA.
  # md5 hashing and temporary files are used not to re-run zifa 
  # if it has already be run on this computer.
  d = digest(Y, "md5")
  tmp = paste0(tempdir(), '/', d)
  write.csv(Y, paste0(tmp, '.csv'))
  
  if (!file.exists(paste0(tmp, "_", k, '_zifa.csv'))){
    print('run ZIFA')
    bb = ifelse(block, '-b ', '')
    cmd = sprintf('python run_zifa.py -d %d %s%s.csv %s_%d_zifa.csv', k, bb, tmp, tmp, k)
    system(cmd)
  }
  read.csv(sprintf("%s_%d_zifa.csv", tmp, k), header=FALSE)
}

zifa_combat <- wrapRzifa(combat, k=2)
```

```{r}
pairs(zifa_combat, pch=19, col=colMerged, main="ZIFA after ComBat")
```

