---
title: 'Espresso: covariates and batch effects'
author: "Davide Risso"
date: "11/17/2016"
output: 
  html_document: 
    fig_height: 7
    fig_width: 7
    toc: yes
    code_folding: hide
    toc_float: yes
---

```{r options, echo=FALSE, results="hide",mesasge=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=TRUE)
library(SummarizedExperiment)
library(scRNAseq)
library(zinb)
library(ggplot2)
library(magrittr)
library(matrixStats)
library(Rtsne)
library(scone)
library(RColorBrewer)
library(cluster)
library(parallel)
library(EDASeq)
library(digest)
library(edgeR)
library(DESeq2)

set.seed(8283)
options(getClass.msg=FALSE) #get rid of annoying messages about cache until fixed internally in R

ncores <- 7
```

Here, I will explore the relation between the expression values and some covariates provided with the data.

```{r datain}
all.counts <- read.table("ESpresso/counttable_es.csv", header=TRUE, row.names=1, colClasses=c("character", rep("integer", 704)))
serum <- sub("ola_mES_([^_]+)_.*", "\\1", colnames(all.counts))
batch <- sub("ola_mES_[^_]+_([^_]+)_.*", "\\1", colnames(all.counts))
targets <- data.frame(Serum=serum, Batch=batch)

# Only using data from two batches.
keep <- targets$Batch %in% c("2", "3")
all.counts <- all.counts[,keep]
targets <- targets[keep,]
targets$Plate <- as.integer(factor(paste0(targets$Serum, targets$Batch)))
targets[] <- lapply(targets, factor)
targets$Serum <- factor(targets$Serum, c("lif", "2i", "a2i"))

# Removing spike-ins.
is.mouse <- grepl("^ENSMUSG", rownames(all.counts))
all.counts <- all.counts[is.mouse,]

col1 <- brewer.pal(9, "Set1")
col2 <- c(brewer.pal(8, "Set2"), brewer.pal(8, "Set3"), brewer.pal(8, "Set1"))

detection_rate <- colSums(all.counts>0)
coverage <- colSums(all.counts)
```

# Comparison of methods

```{r normalization}
filter <- rowSums(all.counts>10)>=10
raw <- all.counts[filter,]

totalcount = function (ei)
{
  sums = colSums(ei)
  eo = t(t(ei)*mean(sums)/sums)
  return(eo)
}

tc <- totalcount(raw)
fq <- FQT_FN(raw)
tmm <- TMM_FN(raw)
deseq <- DESEQ_FN(raw)
```

## PCA

```{r pca}
library(rARPACK)
fastpca <- function(expr, scale=FALSE) {
  svd_raw <- svds(scale(t(expr), center=TRUE, scale=scale), k=3, nu=3, nv=0)
  pc_raw <- svd_raw$u %*% diag(svd_raw$d[1:3])
  return(pc_raw)
}

vars <- rowVars(log1p(tc))
names(vars) <- rownames(tc)
vars <- sort(vars, decreasing = TRUE)
vargenes <- names(vars)[1:1000]


pc_raw <- fastpca(log1p(raw[vargenes,]))
pc_tc <- fastpca(log1p(tc[vargenes,]))
pc_fq <- fastpca(log1p(fq[vargenes,]))
pc_tmm <- fastpca(log1p(tmm[vargenes,]))
#pc_deseq <- fastpca(log1p(deseq))

colMerged <- col1[targets$Serum]
plot(pc_raw, col=colMerged, pch=20, main="PCA RAW")
legend("topleft", levels(targets$Serum), fill=col1)

plot(pc_tc, col=colMerged, pch=20, main="PCA TC")
plot(pc_tmm, col=colMerged, pch=20, main="PCA TMM")
plot(pc_fq, col=colMerged, pch=20, main="PCA FQ")
```

## ZIFA

```{r zifa}
wrapRzifa <- function(Y, block = TRUE, k=2){
  # wrapper R function for ZIFA.
  # md5 hashing and temporary files are used not to re-run zifa 
  # if it has already be run on this computer.
  d = digest(Y, "md5")
  tmp = paste0(tempdir(), '/', d)
  write.csv(Y, paste0(tmp, '.csv'))
  
  if (!file.exists(paste0(tmp, "_", k, '_zifa.csv'))){
    print('run ZIFA')
    bb = ifelse(block, '-b ', '')
    cmd = sprintf('python run_zifa.py -d %d %s%s.csv %s_%d_zifa.csv', k, bb, tmp, tmp, k)
    system(cmd)
  }
  read.csv(sprintf("%s_%d_zifa.csv", tmp, k), header=FALSE)
}

zifa_raw <- wrapRzifa(log1p(raw[vargenes,]), k=2)
pairs(zifa_raw, pch=19, col=colMerged, main="ZIFA Raw")

zifa_tc <- wrapRzifa(log1p(tc[vargenes,]), k=2)
pairs(zifa_tc, pch=19, col=colMerged, main="ZIFA TC")

zifa_tmm <- wrapRzifa(log1p(tmm[vargenes,]), k=2)
pairs(zifa_tmm, pch=19, col=colMerged, main="ZIFA TMM")

zifa_fq <- wrapRzifa(log1p(fq[vargenes,]), k=2)
pairs(zifa_fq, pch=19, col=colMerged, main="ZIFA FQ")
```

## ZINB

```{r zinb}
raw <- as.matrix(raw)
zinb <- zinbFit(raw[vargenes,], ncores = ncores, K = 2, epsilon=1e3)
plot(zinb@W, pch=19, col=colMerged, main="ZINB")
```

## Add batches in ZINB model

```{r zinb_batch}
zinb_batch <- zinbFit(raw[vargenes,], ncores = ncores, K = 2, X=model.matrix(~Batch, data=targets), epsilon=1e3)
plot(zinb_batch@W, pch=19, col=colMerged, main="ZINB")
```

```{r zinb_qc}
library(scater)
rownames(targets) <- colnames(all.counts)
sceset <- newSCESet(countData = all.counts, phenoData = AnnotatedDataFrame(targets))

keep_feature <- rowSums(exprs(sceset) > 0) > 0
sceset <- sceset[keep_feature,]

sceset <- calculateQCMetrics(sceset)
qc <- pData(sceset)[,c(4, 7, 10, 14:17)]
qcpca <- prcomp(qc, scale. = TRUE, center = TRUE)
zinb_qc <- zinbFit(raw[vargenes,], ncores = ncores, K = 2, X=model.matrix(~qcpca$x[,1:2]), epsilon=1e3)
plot(zinb_qc@W, pch=19, col=colMerged, main="ZINB")
```

# Gene-level covariates

```{r gc_content}
gene_info = getGeneLengthAndGCContent(vargenes, "mm10", mode="org.db")

zinb_gc <- zinbFit(raw[vargenes,], ncores = ncores, K = 2, 
                   V=model.matrix(~log(length) + gc, data=as.data.frame(gene_info)),
                   X=model.matrix(~Batch, data=targets),
                   epsilon=1e3)

plot(zinb_gc@W, pch=19, col=colMerged, main="ZINB")

methods <- list(pc_raw[,1:2], pc_tc[,1:2], pc_tmm[,1:2], pc_fq[,1:2],
                zifa_raw, zifa_tc, zifa_tmm, zifa_fq,
                zinb@W, zinb_batch@W, zinb_gc@W)
names(methods) <- c(paste0("PCA_", c("RAW", "TC", "TMM", "FQ")),
                    paste0("ZIFA_", c("RAW", "TC", "TMM", "FQ")),
                    "ZINB", "ZINB_BATCH", "ZINB_GC")

sil_cl <- sapply(seq_along(methods), function(i) {
  d <- dist(methods[[i]])
  ss <- silhouette(as.numeric(targets$Serum), d)
  mean(ss[,3])
})
names(sil_cl) <- names(methods)
barplot(sil_cl, las=3)
```

```{r write_out, dependson=c("zinb", "zifa", "pca", "zinb_batch", "zinb_qc")}
save(zinb, zinb_batch, zinb_qc, zifa_fq, zifa_tmm, zifa_tc, zifa_raw, pc_tmm, pc_fq, pc_tc, pc_raw, file="espresso_covariates.rda")
```
