---
title: "Goodness-of-fit Allen"
author: "Fanny Perraudeau"
date: "03/24/2017"
output: 
  html_document: 
  fig_height: 10
fig_width: 10
toc: yes
code_folding: hide
toc_float: yes
---
```{r options, echo=FALSE, results="hide",message=FALSE, error=FALSE, include=FALSE, autodep=TRUE}
knitr::opts_chunk$set(fig.align="center", cache=TRUE, error=FALSE, message=FALSE, warning=TRUE, fig.width=6, fig.height=6)
library(zinbwave)
library(cellrangerRkit)
library(EDASeq)
library(edgeR)
library(MAST)
library(doParallel)
library(BiocParallel)
```


```{r datain}
pipestance_path <- "tenx_pbmc4k"
pbmc <- load_cellranger_matrix(pipestance_path)
dim(pbmc)
```

```{r zinb}
use_genes <- get_nonzero_genes(pbmc)
dense <- as.matrix(exprs(pbmc[use_genes, ]))

vars <- rowVars(log1p(dense))
names(vars) <- rownames(dense)
vars <- sort(vars, decreasing = TRUE)
vargenes <- names(vars)[1:1000]

core <- dense[vargenes,]

NCORES = 6
registerDoParallel(NCORES)
register(DoparParam())
zinb <- zinbFit(core, K = 0, epsilon = 1e3, commondispersion = TRUE)
```

```{r functions}
computeExp <- function(zinbModel){
  (1 - t(getPi(zinbModel))) * t(getMu(zinbModel))
}

computeVar <- function(zinbModel){
  mu = t(getMu(zinbModel))
  pi = t(getPi(zinbModel))
  phi = exp(-getZeta(zinbModel))
  (1 - pi) * mu * (1 + mu*(phi + pi))
}

computeP0 <- function(zinbModel){
  mu = t(getMu(zinbModel))
  pi = t(getPi(zinbModel))
  phi = exp(-getZeta(zinbModel))
  if(median(phi) < 1e-12) {
    return(pi + (1 - pi) * (exp(-mu)))
  } else {
  return(pi + (1 - pi) * (1 + phi * mu) ^ (-1/phi))    
  }
}

plotMD <- function(x, y, xlim = c(0,10), ylim = c(-5, 5),
                   main = 'ZINB: MD-plot estimated vs. observed mean count, log scale'){
  mm = .5*(x + y)
  dd = x - y
  smoothScatter(mm, dd, xlim = xlim, ylim = ylim, xlab = 'Mean', ylab = 'Difference',
                main = main)
  abline(h = 0, col = 'gray')
  fit = loess(dd ~ mm)
  xpred = seq(0, 10, .1)
  pred = predict(fit, xpred)
  lines(xpred, pred, col = 'red', type = 'l', lwd=2)
}

fitNB <- function(counts){
  set = newSeqExpressionSet(counts)
  fq = EDASeq::betweenLaneNormalization(set, which = "full", offset = T)
  disp = estimateDisp(counts(fq), offset = -offst(fq)) 
  fit = glmFit(counts(fq), dispersion = disp$tagwise.dispersion, offset = -offst(fq))
  list(fitted = fit$fitted.values, disp = disp$tagwise.dispersion)
}
```

```{r nbzinb}
# zinb
zz = zinb
zinbEY = log(rowMeans(computeExp(zz)))
zinbPY0 = rowMeans(computeP0(zz))
# observed
logAveCount = log(rowMeans(core))
prop0 = rowMeans(core == 0)

# edgeR
nb = fitNB(core)
nbEY = log(rowMeans(nb$fitted))
nbPY0 = rowMeans((1 + nb$fitted * nb$disp)^(-1/nb$disp))
```


```{r mast}
invlogit = function(x) 1/(1 + exp(-x))

sca = newSeqExpressionSet(core)
sca = FromMatrix(log1p(counts(sca)))
fit <- zlm(~ 1, sca)
X = model.matrix(~ rep(1, ncol(sca)) + 0)
P_z_0 = 1 - invlogit(coef(fit, 'D') %*% t(X))
exp_mean_gaussian = exp(coef(fit, 'C') %*% t(X))
var_gaussian = fit@dispersion[,'C']
P_gaussian_0 = (1/sqrt(2*pi*var_gaussian))* exp(-0.5 * log(exp_mean_gaussian)^2 / var_gaussian)
EY = ( (1 - P_z_0) / (1 - P_gaussian_0) ) * exp_mean_gaussian
hurdleEY = rowMeans(log(EY))
hurdlePY0 = rowMeans(P_z_0)
```

MD-plot estimated vs. observed mean count, log scale
```{r plot1}
pdf("gof_10X_mu.pdf", width = 10, height = 5)
par(mfrow=c(1,3))
xlim =  c(-1.5, 5.5)
ylim = c(-1, 1)
plotMD(zinbEY, logAveCount, xlim = xlim, ylim = ylim, main = 'ZINB, ZINB-WaVE')
plotMD(hurdleEY, rowMeans(log1p(core)), xlim = xlim, ylim = ylim, main = 'Hurdle, MAST')
plotMD(nbEY, logAveCount, xlim = xlim, ylim = ylim, main = 'NB, edgeR')
dev.off()
```

MD-plot estimated vs. observed zero probability
```{r plot2}
pdf("gof_10X_pi.pdf", width = 10, height = 5)
par(mfrow = c(1, 3))
plotMD(zinbPY0, prop0, xlim = c(0, .8), ylim = c(-.2, .1), main = 'ZINB, ZINB-WaVE')
plotMD(hurdlePY0, prop0, xlim = c(0, .8), ylim = c(-.2, .1), main = 'Hurdle, MAST')
plotMD(nbPY0, prop0, xlim = c(0, .8), ylim = c(-.2, .1), main = 'NB, edgeR')
dev.off()
```

Estimated dispersion versus observed zero probability
```{r plot3}
pdf("gof_10X_disp.pdf", width = 10, height = 5)
par(mfrow = c(1,3))
xpred = seq(0, 1, .05)
fitzinb = loess(exp(-zz@zeta) ~ rowMeans(core == 0))
predzinb = predict(fitzinb, xpred)
fitnb = loess(nb$disp ~ rowMeans(core == 0))
prednb = predict(fitnb, xpred)
fithurdle = loess(var_gaussian ~ rowMeans(core == 0))
predhurdle = predict(fithurdle, xpred)

smoothScatter(rowMeans(core == 0), exp(-zz@zeta),
              xlab = 'Observed zero probability',ylim = c(0, 1),
              ylab = 'Estimated dispersion',xlim = c(0,1), 
              main = 'ZINB, ZINB-WaVE', bandwidth = c(0.1, 0.01))
lines(xpred, predzinb, col = 'red', type = 'l', lwd=2)

smoothScatter(rowMeans(core == 0), var_gaussian,
              xlab = 'Observed zero probability',ylim = c(0, 5),
              ylab = 'Estimated gaussian variance',xlim = c(0,1), 
              main = 'Hurdle, MAST')
lines(xpred, predhurdle, col = 'red', type = 'l', lwd=2)

smoothScatter(rowMeans(core == 0), nb$disp,
              xlab = 'Observed zero probability',ylim = c(0, 5),
              ylab = 'Estimated dispersion',xlim = c(0,1), 
              main = 'NB, edgeR')
lines(xpred, prednb, col = 'red', type = 'l', lwd=2)
dev.off()
```


